"""
Generate GitHub Actions workflow YAML for EPAC pipelines.

Usage::

    from epac.integrations.github import generate_workflow_yaml
    yaml = generate_workflow_yaml(trigger="issue_comment")
    Path(".github/workflows/epac.yml").write_text(yaml)
"""

from __future__ import annotations

from typing import Literal


def generate_workflow_yaml(
    trigger: Literal["issue_comment", "workflow_dispatch", "schedule"] = "issue_comment",
    python_version: str = "3.11",
    epac_version: str = ">=0.1.0",
    critic_tools: list[str] | None = None,
    autonomy_level: int = 3,
    include_sarif_upload: bool = True,
) -> str:
    """
    Generate a GitHub Actions workflow YAML file for EPAC pipelines.

    Parameters
    ----------
    trigger:
        What triggers the workflow:
        - "issue_comment": Expert comments "/epac run" on a GitHub Issue
        - "workflow_dispatch": Manual trigger with input fields
        - "schedule": Cron-based trigger
    python_version:
        Python version to use in the runner
    epac_version:
        pip version specifier for the epac package
    critic_tools:
        List of Critic tool integrations to enable
    autonomy_level:
        Default autonomy level (1-5)
    include_sarif_upload:
        Whether to upload Critic SARIF to GitHub Code Scanning
    """
    critic_tools = critic_tools or ["bandit", "semgrep", "github_code_scanning"]

    trigger_yaml = _build_trigger(trigger)
    sarif_step = _build_sarif_step() if include_sarif_upload else ""

    return f"""# EPAC Pipeline – Expert-Planner-Actor-Critic Workflow
# Generated by epac.integrations.github.generate_workflow_yaml()
# Docs: https://github.com/thomason-io/epac

name: EPAC Pipeline

{trigger_yaml}

permissions:
  contents: write        # Actor: create branches and commits
  pull-requests: write   # Actor: open pull requests
  issues: write          # Expert: comment on issues
  security-events: write # Critic: upload SARIF to Code Scanning
  id-token: write        # OIDC for secret broker (optional)

jobs:
  epac:
    name: EPAC Expert→Planner→Actor→Critic
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"
          cache: pip

      - name: Install EPAC and tools
        run: |
          pip install "epac[github,litellm]{epac_version}"
          pip install bandit semgrep

      - name: Run EPAC pipeline
        id: epac_run
        env:
          OPENAI_API_KEY: ${{{{ secrets.OPENAI_API_KEY }}}}
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
          GITHUB_REPOSITORY: ${{{{ github.repository }}}}
          EPAC_BASE_BRANCH: ${{{{ github.event.repository.default_branch }}}}
          EPAC_AUTONOMY_LEVEL: "{autonomy_level}"
          EPAC_CRITIC_TOOLS: "{",".join(critic_tools)}"
        run: |
          python -m epac.cli run \\
            --goal "${{{{ github.event.issue.body || inputs.goal }}}}" \\
            --expert-id "${{{{ github.actor }}}}" \\
            --output-file epac-result.json
{sarif_step}
      - name: Post result to issue/PR
        if: always()
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          python -m epac.cli report \\
            --result-file epac-result.json \\
            --post-github-comment

      - name: Upload pipeline artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: epac-pipeline-${{{{ github.run_id }}}}
          path: |
            epac-result.json
            epac-audit.json
          retention-days: 90
"""


def _build_trigger(trigger: str) -> str:
    if trigger == "issue_comment":
        return """on:
  issue_comment:
    types: [created]

# Only run when Expert comments "/epac run" on an issue (not a PR)
# Add further filters (e.g. label checks) as needed for your governance model.
"""
    elif trigger == "workflow_dispatch":
        return """on:
  workflow_dispatch:
    inputs:
      goal:
        description: "High-level goal for the EPAC pipeline"
        required: true
        type: string
      risk_level:
        description: "Risk level (low / medium / high / critical)"
        required: false
        default: medium
        type: choice
        options: [low, medium, high, critical]
"""
    elif trigger == "schedule":
        return """on:
  schedule:
    - cron: "0 9 * * 1-5"  # Weekdays at 09:00 UTC — adjust as needed
  workflow_dispatch: {}
"""
    return f"on:\n  push: {{}}\n"


def _build_sarif_step() -> str:
    return """
      - name: Upload Critic SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: epac-critic.sarif
          category: epac-critic
"""
